server:
  host: localhost
  port: 8000
  log_level: INFO

qdrant:
  url: http://localhost:6333
  collection_name: cursor_context
  api_key: ${QDRANT_API_KEY}

openai:
  model: text-embedding-3-small
  max_tokens: 8191
  api_key: ${OPENAI_API_KEY}

search:
  default_limit: 10
  max_limit: 50
  min_score: 0.7
  source_types:
    - git
    - confluence
    - jira 